### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by frogcrush** [SamuelFisher/torrentcore#1]
Is there a Nuget package available for this?

**Comment by SamuelFisher** [comment]
Yes, there are instructions [here](https://torrentcore.org/getting-started/) for how to install it as a NuGet package. There aren't any stable releases yet but you can install by adding this to your `NuGet.config` file:

```xml
<configuration>
  <packageSources>
    <add key="TorrentCore-AppVeyor" value="https://ci.appveyor.com/nuget/torrentcore-0je3uyk11790" />
  </packageSources>
</configuration>
```

And then installing the `TorrentCore` package. This will pick up the latest version from the AppVeyor CI build.

**Comment by ffMathy** [comment]
The given instructions no longer work.

**Comment by ffMathy** [comment]
This is also easier than ever with GitHub Actions!
