### ISSUE TITLE
How to use a custom transport protocol?

### ISSUE THREAD

**Issue by kinosang** [SamuelFisher/torrentcore#2]
I didn't find any way to use custom transport when create instances of `TorrentClient`.

https://github.com/SamuelFisher/torrentcore/blob/08ed67daacd80aaec74b01e988847cb44e9f1f59/TorrentCore/TorrentClient.cs#L61-L65

**Comment by SamuelFisher** [comment]
This has been added:

https://github.com/SamuelFisher/torrentcore/blob/241903ceddd8f0a70004d8f7ea4914aead99c72b/TorrentCore/TorrentClient.cs#L39-L42

**Comment by SamuelFisher** [comment]
There is now a full example of this - please see:

[examples/CustomTransportProtocol](https://github.com/SamuelFisher/torrentcore/tree/master/examples/CustomTransportProtocol)
