### ISSUE TITLE
Extract an interface for the TorrentClient class

### ISSUE THREAD

**Issue by SeanFarrow** [SamuelFisher/torrentcore#3]
I'm just about to start using this in a project and noticed whilst looking at the code that the TorrentClient class does not have a corresponding interface.

This means consumers of the library may not easily be able to unit test the interactions with this particular external code.

Would you consider extracting an ITorrentClient interface, or accepting a pull request?
Thanks,
Sean.

**Comment by SamuelFisher** [comment]
An `ITorrentClient` interface has now been added:

https://github.com/SamuelFisher/torrentcore/blob/241903ceddd8f0a70004d8f7ea4914aead99c72b/TorrentCore/ITorrentClient.cs#L21
